git clone git@github.com:0x55aa/golang-udp-chat
git clone git@github.com:AlanQuatermain/go-apns
git clone git@github.com:ChimeraCoder/anaconda
git clone git@github.com:HouzuoGuo/tiedot
git clone git@github.com:JeffPaine/ht
git clone git@github.com:Nightgunner5/go.db
git clone git@github.com:SlyMarbo/rss
git clone git@github.com:SlyMarbo/spdy
git clone git@github.com:Terry-Mao/gopush-cluster
git clone git@github.com:VividCortex/godaemon
git clone git@github.com:abbot/go-http-auth
git clone git@github.com:ahmetalpbalkan/go-linq
git clone git@github.com:akrennmair/cyder
git clone git@github.com:akrennmair/drunken-hipster
git clone git@github.com:akrennmair/epos
git clone git@github.com:akrennmair/glip
git clone git@github.com:akrennmair/gobox
git clone git@github.com:akrennmair/gockel
git clone git@github.com:anachronistic/apns
git clone git@github.com:anandkunal/goq
git clone git@github.com:ant0ine/go-json-rest
git clone git@github.com:astaxie/beego
git clone git@github.com:aybabtme/uniplot
git clone git@github.com:azer/atlas
git clone git@github.com:badgerodon/peg
git clone git@github.com:barakmich/switchyard
git clone git@github.com:bashtian/jsonutils
git clone git@github.com:beego/bee
git clone git@github.com:beego/beeblog
git clone git@github.com:beego/beedoc
git clone git@github.com:beego/example
git clone git@github.com:beego/modules
git clone git@github.com:beego/samples
git clone git@github.com:beego/social-auth
git clone git@github.com:belogik/goes
git clone git@github.com:benmanns/goworker
git clone git@github.com:bfix/gospel
git clone git@github.com:bfix/sid
git clone git@github.com:bfix/sid_custom
git clone git@github.com:bitly/go-simplejson
git clone git@github.com:bitly/nsq
git clone git@github.com:bmizerany/pat
git clone git@github.com:boltdb/bolt
git clone git@github.com:bradfitz/camlistore
git clone git@github.com:bradfitz/campher
git clone git@github.com:bradfitz/gitbrute
git clone git@github.com:bradfitz/go-smtpd
git clone git@github.com:bradfitz/goimports
git clone git@github.com:bradfitz/gomemcache
git clone git@github.com:bradfitz/iter
git clone git@github.com:bradfitz/runsit
git clone git@github.com:bradfitz/shipit
git clone git@github.com:bradfitz/slice
git clone git@github.com:bradfitz/webfist
git clone git@github.com:bradfitz/websomtep
git clone git@github.com:buger/gor
git clone git@github.com:burnto/spot
git clone git@github.com:calmh/syncthing
git clone git@github.com:camlistore/goexif
git clone git@github.com:camlistore/lock
git clone git@github.com:campoy/gameoflife
git clone git@github.com:campoy/gas
git clone git@github.com:campoy/gophurls
git clone git@github.com:campoy/newtodo
git clone git@github.com:campoy/sortslice
git clone git@github.com:campoy/todo
git clone git@github.com:cheggaaa/pb
git clone git@github.com:chihaya/chihaya
git clone git@github.com:cloudfoundry/gorouter
git clone git@github.com:cloudson/gitql
git clone git@github.com:cockroachdb/cockroach
git clone git@github.com:codegangsta/cli
git clone git@github.com:codegangsta/confab
git clone git@github.com:codegangsta/dotfiles
git clone git@github.com:codegangsta/envy
git clone git@github.com:codegangsta/gin
git clone git@github.com:codegangsta/go-advent-martini
git clone git@github.com:codegangsta/inject
git clone git@github.com:codegangsta/negroni
git clone git@github.com:codegangsta/pompom
git clone git@github.com:codegangsta/spotify
git clone git@github.com:conformal/btcd
git clone git@github.com:coopernurse/gorp
git clone git@github.com:coreos/etcd
git clone git@github.com:coreos/fleet
git clone git@github.com:coreos/go-etcd
git clone git@github.com:cznic/b
git clone git@github.com:cznic/bufs
git clone git@github.com:cznic/dns
git clone git@github.com:cznic/ebnf
git clone git@github.com:cznic/ebnf2y
git clone git@github.com:cznic/ebnfutil
git clone git@github.com:cznic/exp
git clone git@github.com:cznic/fileutil
git clone git@github.com:cznic/fsm
git clone git@github.com:cznic/golex
git clone git@github.com:cznic/js
git clone git@github.com:cznic/kv
git clone git@github.com:cznic/lex
git clone git@github.com:cznic/lexer
git clone git@github.com:cznic/mathutil
git clone git@github.com:cznic/otto2js
git clone git@github.com:cznic/parser
git clone git@github.com:cznic/ql
git clone git@github.com:cznic/scanner
git clone git@github.com:cznic/sortutil
git clone git@github.com:cznic/strutil
git clone git@github.com:cznic/tmp
git clone git@github.com:cznic/zappy
git clone git@github.com:ddollar/forego
git clone git@github.com:deckarep/gosx-notifier
git clone git@github.com:disintegration/imaging
git clone git@github.com:diwakergupta/gaestebin
git clone git@github.com:docker/libchan
git clone git@github.com:docker/libswarm
git clone git@github.com:docopt/docopt.go
git clone git@github.com:dotcloud/docker
git clone git@github.com:dougblack/sleepy
git clone git@github.com:dropbox/godropbox
git clone git@github.com:dsymonds/fixhub
git clone git@github.com:dsymonds/gmail
git clone git@github.com:dsymonds/goembed
git clone git@github.com:dsymonds/gotoc
git clone git@github.com:dustin/go-humanize
git clone git@github.com:dustin/gomemcached
git clone git@github.com:dustin/seriesly
git clone git@github.com:emicklei/go-restful
git clone git@github.com:fatih/set
git clone git@github.com:fatiherikli/worldcup
git clone git@github.com:garyburd/redigo
git clone git@github.com:garyburd/tango
git clone git@github.com:gin-gonic/gin
git clone git@github.com:go-llvm/llgo
git clone git@github.com:go-llvm/llvm
git clone git@github.com:go-martini/martini
git clone git@github.com:/go-sql-driver/mysql
git clone git@github.com:go-xorm/xorm
git clone git@github.com:go-xorm/xorm
git clone git@github.com:go-xorm/xorm
git clone git@github.com:gocircuit/circuit
git clone git@github.com:gogits/gogs
git clone git@github.com:goinaction/code
git clone git@github.com:gokyle/opmlfeed
git clone git@github.com:golang/gddo
git clone git@github.com:golang/groupcache
git clone git@github.com:google/cayley
git clone git@github.com:google/go-github
git clone git@github.com:goraft/raft
git clone git@github.com:gorilla/context
git clone git@github.com:gorilla/feeds
git clone git@github.com:gorilla/handlers
git clone git@github.com:gorilla/http
git clone git@github.com:gorilla/mux
git clone git@github.com:gorilla/pat
git clone git@github.com:gorilla/reverse
git clone git@github.com:gorilla/rpc
git clone git@github.com:gorilla/securecookie
git clone git@github.com:gorilla/websocket
git clone git@github.com:gsempe/retwis-go
git clone git@github.com:ha/doozer
git clone git@github.com:ha/doozerd
git clone git@github.com:harlanji/gogherkit
git clone git@github.com:hashicorp/memberlist
git clone git@github.com:hkolasani/gomongo
git clone git@github.com:hoisie/redis
git clone git@github.com:hoisie/web
git clone git@github.com:hoverruan/send-apns
git clone git@github.com:howeyc/fsnotify
git clone git@github.com:hypebeast/go-osc
git clone git@github.com:icub3d/goblog
git clone git@github.com:icub3d/joshua.themarshians.com
git clone git@github.com:igrigorik/canicrawl
git clone git@github.com:influxdb/influxdb
git clone git@github.com:jackpal/Taipei-Torrent
git clone git@github.com:jbarham/pgsql.go
git clone git@github.com:jcla1/gisp
git clone git@github.com:jessta/gobit
git clone git@github.com:jgallagher/go-libpq
git clone git@github.com:jinzhu/gorm
git clone git@github.com:jmhodges/levigo
git clone git@github.com:jmoiron/sqlx
git clone git@github.com:joewalnes/websocketd
git clone git@github.com:jonlawlor/rel
git clone git@github.com:jordan-wright/email
git clone git@github.com:josharian/countselectcases
git clone git@github.com:julian-gutierrez-o/rsync
git clone git@github.com:julienschmidt/httprouter
git clone git@github.com:justinas/alice
git clone git@github.com:kaicheng/jobmux
git clone git@github.com:kelseyhightower/confd
git clone git@github.com:kurrik/twittergo
git clone git@github.com:kurrik/twittergo-examples
git clone git@github.com:kz26/gohls
git clone git@github.com:lamaofruin/opml
git clone git@github.com:lann/squirrel
git clone git@github.com:lib/pq
git clone git@github.com:limetext/lime
git clone git@github.com:lxn/go-pgsql
git clone git@github.com:mailgun/vulcan
git clone git@github.com:martine/gen
git clone git@github.com:martine/go-imap
git clone git@github.com:martini-contrib/acceptlang
git clone git@github.com:martini-contrib/accessflags
git clone git@github.com:martini-contrib/auth
git clone git@github.com:martini-contrib/binding
git clone git@github.com:martini-contrib/cors
git clone git@github.com:martini-contrib/csrf
git clone git@github.com:martini-contrib/encoder
git clone git@github.com:martini-contrib/gorelic
git clone git@github.com:martini-contrib/gzip
git clone git@github.com:martini-contrib/logstasher
git clone git@github.com:martini-contrib/method
git clone git@github.com:martini-contrib/oauth2
git clone git@github.com:martini-contrib/render
git clone git@github.com:martini-contrib/secure
git clone git@github.com:martini-contrib/sessionauth
git clone git@github.com:martini-contrib/sessions
git clone git@github.com:martini-contrib/staticbin
git clone git@github.com:martini-contrib/strict
git clone git@github.com:martini-contrib/strip
git clone git@github.com:martini-contrib/throttle
git clone git@github.com:martini-contrib/web
git clone git@github.com:mattbaird/elastigo
git clone git@github.com:mattn/anko
git clone git@github.com:mattn/go-sqlite3
git clone git@github.com:mattn/go-xmpp
git clone git@github.com:mattn/gom
git clone git@github.com:mbk/tcb
git clone git@github.com:mdlayher/goat.git
git clone git@github.com:mitchellh/packer
git clone git@github.com:mkaz/working-with-go
git clone git@github.com:mmcgrana/pgpin
git clone git@github.com:mmcgrana/tidytrello
git clone git@github.com:motemen/ghq
git clone git@github.com:muhqu/go-gherkin
git clone git@github.com:mynameisfiber/gocountme
git clone git@github.com:ncw/directio
git clone git@github.com:ncw/gmp
git clone git@github.com:ncw/swift
git clone git@github.com:nf/bounce
git clone git@github.com:nf/gohttptun
git clone git@github.com:nf/goplayer
git clone git@github.com:nf/hn-watch
git clone git@github.com:nf/sigourney
git clone git@github.com:nickoneill/go-dropbox
git clone git@github.com:nictuku/dht
git clone git@github.com:nsf/gocode
git clone git@github.com:nsf/godit
git clone git@github.com:nsf/gollvm
git clone git@github.com:nsf/libtorgo
git clone git@github.com:nsf/termbox
git clone git@github.com:nsf/termbox-go
git clone git@github.com:nsf/torgo
git clone git@github.com:nytlabs/gojee.git
git clone git@github.com:nytlabs/gojsonexplode
git clone git@github.com:nytlabs/streamtools
git clone git@github.com:nytlabs/streamtools-demos.git
git clone git@github.com:nytlabs/streamtools.git
git clone git@github.com:oguzbilgic/pandik
git clone git@github.com:oysterbooks/halfshell
git clone git@github.com:packetbeat/packetbeat
git clone git@github.com:peco/peco
git clone git@github.com:petar/GoDCCP
git clone git@github.com:petar/GoHTTP
git clone git@github.com:petar/GoLLRB
git clone git@github.com:petar/GoTeleport
git clone git@github.com:peterbourgon/diskv
git clone git@github.com:peterbourgon/elasticsearch
git clone git@github.com:peterbourgon/g2g
git clone git@github.com:peterbourgon/g2s
git clone git@github.com:peterbourgon/gmd
git clone git@github.com:peterbourgon/goop
git clone git@github.com:peterbourgon/got
git clone git@github.com:peterbourgon/grender
git clone git@github.com:peterbourgon/numberstation
git clone git@github.com:peterbourgon/raft
git clone git@github.com:peterbourgon/rp
git clone git@github.com:peterbourgon/seq
git clone git@github.com:peterbourgon/srvproxy
git clone git@github.com:peterbourgon/termbox
git clone git@github.com:peterbourgon/yo
git clone git@github.com:piranha/gostatic
git clone git@github.com:pmylund/go-cache
git clone git@github.com:pquerna/ffjson
git clone git@github.com:prasmussen/gdrive
git clone git@github.com:prometheus/prometheus
git clone git@github.com:pushrax/serve
git clone git@github.com:rakyll/boom
git clone git@github.com:rcrowley/go-tigertonic
git clone git@github.com:remyoudompheng/go-dns
git clone git@github.com:remyoudompheng/go-misc
git clone git@github.com:remyoudompheng/gocash
git clone git@github.com:revel/revel
git clone git@github.com:robertkrimen/otto
git clone git@github.com:russross/blackfriday
git clone git@github.com:sdming/kdb
git clone git@github.com:secondbit/wendy
git clone git@github.com:sekhat/mist
git clone git@github.com:settermjd/Learning-Beego
git clone git@github.com:shanemhansen/goapns
git clone git@github.com:shirou/gopsutil
git clone git@github.com:shurcooL/markdownfmt
git clone git@github.com:sirupsen/logrus
git clone git@github.com:sjwhitworth/golearn
git clone git@github.com:skydb/sky
git clone git@github.com:smartystreets/goconvey
git clone git@github.com:soundcloud/eagle
git clone git@github.com:soundcloud/ent
git clone git@github.com:soundcloud/roshi
git clone git@github.com:soundcloud/roshi.git
git clone git@github.com:sourcegraph/webloop
git clone git@github.com:spf13/cobra
git clone git@github.com:spf13/dagobah
git clone git@github.com:spf13/hugo
git clone git@github.com:spf13/hugoThemes
git clone git@github.com:steveyen/gkvlite
git clone git@github.com:streadway/handy
git clone git@github.com:stripe-ctf/octopus
git clone git@github.com:syndtr/goleveldb
git clone git@github.com:tcnksm/cli-init
git clone git@github.com:timtadh/data-structures
git clone git@github.com:tools/godep
git clone git@github.com:torrance/enforced
git clone git@github.com:tsenart/vegeta
git clone git@github.com:tstromberg/verbalize
git clone git@github.com:tux21b/ChessBuddy
git clone git@github.com:ungerik/go-rest
git clone git@github.com:unrolled/gapless
git clone git@github.com:unrolled/render
git clone git@github.com:unrolled/secure
git clone git@github.com:vole/btsync-api
git clone git@github.com:whee/adn
git clone git@github.com:youtube/vitess
git clone git@github.com:zachlatta/postman
git clone git@github.com:zenazn/goji
git clone git@github.com:zenazn/goji.git
git clone git@github.com:zhemao/glisp
git clone git@github.com:zond/god
git clone git@github.com:zond/gotomic
